-- Octopus C04 prototype — hosted Supabase (Free) schema.
--
-- Only simulated interaction events and human reviewer decisions are stored here.
-- The supplied exercise records stay in source/initial.json and are never written to Supabase.
--
-- Apply with: supabase db push  (or paste into the SQL editor of the hosted project).

create table if not exists public.c04_events (
    id          bigint generated by default as identity primary key,
    created_at  timestamptz not null default now(),
    case_id     text        not null default 'C04',
    kind        text        not null,   -- receipt_confirmed | evidence_linked | rc2_simulated | repeated_scan_simulated | scan_review_resolved
    payload     jsonb       not null default '{}'::jsonb,
    simulated   boolean     not null default true
);

create table if not exists public.c04_decisions (
    id            bigint generated by default as identity primary key,
    created_at    timestamptz not null default now(),
    case_id       text        not null default 'C04',
    decision      text        not null check (decision in ('approved', 'corrected', 'unresolved')),
    explanation   text        not null,           -- the deterministic explanation that was reviewed
    correction    text,                            -- reviewer correction, when the explanation was wrong
    engine_version text       not null,
    snapshot      jsonb       not null default '{}'::jsonb
);

create index if not exists c04_events_case_id_idx on public.c04_events (case_id, id);
create index if not exists c04_decisions_case_id_idx on public.c04_decisions (case_id, id);

-- Row level security is enabled with no policies on purpose: nothing is reachable
-- with an anon or publishable key. The app talks to these tables from its server
-- routes with the secret key, which bypasses RLS. Add policies here if a future
-- read path ever needs to run against the public API.
alter table public.c04_events enable row level security;
alter table public.c04_decisions enable row level security;

-- ---------------------------------------------------------------------------
-- Synthetic demo-case catalog (prototype only).
--
-- This is NOT the production reconciliation domain model. It exists so the
-- receipt-entry screen can offer three labelled synthetic deliveries and so the
-- mocked "ERP/order lookup" resolves an identifier to a case snapshot.
-- Server routes read it with SUPABASE_SECRET_KEY; RLS is on with no policies.
-- ---------------------------------------------------------------------------

create table if not exists public.c04_demo_cases (
    case_id text primary key,
    delivery_note text not null unique,
    purchase_order text not null,
    part_number text not null,
    display_name text not null,
    fixture jsonb not null default '{}'::jsonb,
    synthetic boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.c04_demo_cases enable row level security;

-- Idempotent seeds: safe to re-run.
insert into public.c04_demo_cases
    (case_id, delivery_note, purchase_order, part_number, display_name, fixture, synthetic)
values
    (
        'C04-FILTER-X',
        'DN-1',
        'PO-1',
        'FILTER-X',
        'Filter X · staged delivery',
        '{"ordered":10,"initial_received":8,"damaged":1,"accepted":7,"invoiced":10,"later_received_adds":2,"later_delivery_note":"DN-2","later_receipt":"RC-2","initial_receipt":"RC-1","invoice":"INV-1","later_simulation":true,"expected_result":"possible shortage, then damage only after RC-2"}'::jsonb,
        true
    ),
    (
        'C04-AIR-FILTER',
        'DN-20',
        'PO-20',
        'AIR-FILTER-Y',
        'Air filter Y · clean match',
        '{"ordered":20,"initial_received":20,"damaged":0,"accepted":20,"invoiced":20,"later_received_adds":0,"initial_receipt":"RC-20","invoice":"INV-20","later_simulation":false,"expected_result":"matched"}'::jsonb,
        true
    ),
    (
        'C04-BRAKE-DISC',
        'DN-30',
        'PO-30',
        'BRAKE-DISC-Z',
        'Brake disc Z · damage exception',
        '{"ordered":12,"initial_received":12,"damaged":2,"accepted":10,"invoiced":12,"later_received_adds":0,"initial_receipt":"RC-30","invoice":"INV-30","later_simulation":false,"expected_result":"damage exception requiring review"}'::jsonb,
        true
    )
on conflict (case_id) do update set
    delivery_note = excluded.delivery_note,
    purchase_order = excluded.purchase_order,
    part_number = excluded.part_number,
    display_name = excluded.display_name,
    fixture = excluded.fixture,
    synthetic = excluded.synthetic;
