"""Deterministic reconciliation engine for Octopus case C04.

No model is called at run time. Every number and every sentence in the output is
derived from the supplied records in ``source/initial.json`` plus the evidence the
reviewer has linked, by the pure functions in this module.

Rules honoured (from the supplied ``rules`` block):
  * received, damaged and accepted quantities are kept separate;
  * one scan is not necessarily one new delivery (a repeated scan without a unique
    package identity must never increase the received quantity);
  * no stock, accounting or supplier action is generated by this engine.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

from .records import Records

ENGINE_VERSION = "c04-recon-1"

ObservationKind = Literal["delivery", "repeated_scan"]
ConclusionStatus = Literal["derived", "missing"]


@dataclass(frozen=True)
class Observation:
    """A physical arrival observation confirmed at the loading bay."""

    id: str
    kind: ObservationKind
    received: int
    damaged: int
    source_record: str | None = None
    delivery_note: str | None = None
    package_identity: str | None = None
    label: str = ""


@dataclass(frozen=True)
class CaseFacts:
    """Snapshot of a synthetic catalogue case.

    Present only for the additional demo cases. When it is absent every quantity is
    derived from the supplied records in ``source/initial.json`` exactly as before,
    so the FILTER-X behaviour and its tests are untouched.
    """

    case_id: str = ""
    part_number: str = ""
    ordered: int | None = None
    invoiced: int | None = None
    listed: int | None = None


@dataclass(frozen=True)
class EvidenceContext:
    order_ids: tuple[str, ...] = ()
    delivery_note_ids: tuple[str, ...] = ()
    receipt_ids: tuple[str, ...] = ()
    invoice_ids: tuple[str, ...] = ()
    observations: tuple[Observation, ...] = ()
    facts: CaseFacts | None = None


@dataclass
class Conclusion:
    id: str
    label: str
    value: int | str
    unit: str
    source: list[str] = field(default_factory=list)
    calculation: str = ""
    status: ConclusionStatus = "derived"


def compute(ctx: EvidenceContext, records: Records) -> dict[str, Any]:
    """Pure reconciliation. The same input always yields the same output."""
    deliveries = [o for o in ctx.observations if o.kind == "delivery"]
    repeated = [o for o in ctx.observations if o.kind == "repeated_scan"]
    unidentified = [o for o in repeated if not o.package_identity]

    received = sum(o.received for o in deliveries)
    damaged = sum(o.damaged for o in deliveries)
    accepted = received - damaged

    linked_orders = [o for o in (records.order(i) for i in ctx.order_ids) if o is not None]
    linked_dns = [d for d in (records.delivery_note(i) for i in ctx.delivery_note_ids) if d is not None]
    linked_invs = [i for i in (records.invoice(i) for i in ctx.invoice_ids) if i is not None]
    linked_rcs = [r for r in (records.receipt(i) for i in ctx.receipt_ids) if r is not None]

    facts = ctx.facts
    invoiced = (
        facts.invoiced
        if facts is not None and facts.invoiced is not None
        else (sum(i.quantity for i in linked_invs) if linked_invs else None)
    )
    listed = (
        facts.listed
        if facts is not None and facts.listed is not None
        else (sum(d.listed_quantity for d in linked_dns) if linked_dns else None)
    )
    # When a catalogue case supplies the billed quantity, name that source rather
    # than implying a supplied invoice record exists.
    invoice_source = [i.id for i in linked_invs] or (
        [f"catalogue fixture · {facts.case_id}"]
        if facts is not None and facts.invoiced is not None
        else []
    )

    shortage = max(invoiced - received, 0) if invoiced is not None else None
    overage = max(received - invoiced, 0) if invoiced is not None else 0
    unlisted_arrivals = max(received - listed, 0) if listed is not None else 0

    def chain(pairs: list[tuple[str, int]], field_name: str) -> str:
        return " + ".join(f"{rid}.{field_name}({val})" for rid, val in pairs) or "no confirmed arrival observation"

    recv_pairs = [(o.source_record or o.id, o.received) for o in deliveries]
    dmg_pairs = [(o.source_record or o.id, o.damaged) for o in deliveries]

    conclusions: list[Conclusion] = [
        Conclusion(
            id="CON-RECEIVED",
            label="Received quantity",
            value=received,
            unit="unit(s)",
            source=[p[0] for p in recv_pairs],
            calculation=chain(recv_pairs, "received"),
        ),
        Conclusion(
            id="CON-DAMAGED",
            label="Damaged quantity",
            value=damaged,
            unit="unit(s)",
            source=[p[0] for p in dmg_pairs],
            calculation=chain(dmg_pairs, "damaged"),
        ),
        Conclusion(
            id="CON-ACCEPTED",
            label="Accepted quantity",
            value=accepted,
            unit="unit(s)",
            source=[p[0] for p in recv_pairs],
            calculation=f"received({received}) - damaged({damaged}) = {accepted}",
        ),
    ]

    if invoiced is not None:
        conclusions += [
            Conclusion(
                id="CON-INVOICED",
                label="Invoiced quantity",
                value=invoiced,
                unit="unit(s)",
                source=invoice_source,
                calculation=" + ".join(f"{i.id}.quantity({i.quantity})" for i in linked_invs),
            ),
            Conclusion(
                id="CON-SHORTAGE",
                label="Possible shortage",
                value=shortage or 0,
                unit="unit(s)",
                source=invoice_source + [p[0] for p in recv_pairs],
                calculation=f"invoiced({invoiced}) - received({received}) = {shortage}",
            ),
        ]
    else:
        conclusions.append(
            Conclusion(
                id="CON-SHORTAGE",
                label="Possible shortage",
                value="not computable",
                unit="",
                source=[],
                calculation="no invoice linked; shortage cannot be calculated",
                status="missing",
            )
        )

    if listed is not None:
        conclusions.append(
            Conclusion(
                id="CON-LISTED",
                label="Listed on linked delivery note(s)",
                value=listed,
                unit="unit(s)",
                source=[d.id for d in linked_dns],
                calculation=" + ".join(f"{d.id}.listed_quantity({d.listed_quantity})" for d in linked_dns),
            )
        )

    if repeated:
        conclusions.append(
            Conclusion(
                id="CON-REPEATED-SCAN",
                label="Repeated scans excluded from received quantity",
                value=len(unidentified),
                unit="scan(s)",
                source=[o.id for o in repeated],
                calculation=(
                    "scan without unique package identity is not a new delivery; "
                    f"received quantity unchanged at {received}"
                ),
            )
        )

    evidence: list[dict[str, Any]] = []
    for o in linked_orders:
        evidence.append(
            {
                "id": o.id,
                "kind": "order",
                "label": f"Purchase order · {o.part} x {o.quantity}",
                "detail": f"Ordered quantity {o.quantity}. Expectation source for the whole reconciliation.",
                "source": "source/initial.json",
            }
        )
    for d in linked_dns:
        evidence.append(
            {
                "id": d.id,
                "kind": "delivery_note",
                "label": f"Delivery note · {d.part} x {d.listed_quantity}",
                "detail": f"Covers {d.listed_quantity} unit(s) for {d.order_id}.",
                "source": "source/initial.json",
            }
        )
    for r in linked_rcs:
        evidence.append(
            {
                "id": r.id,
                "kind": "receipt",
                "label": f"Receipt observation · received {r.received} / damaged {r.damaged} / accepted {r.accepted}",
                "detail": "What was physically recorded at the loading bay.",
                "source": "source/initial.json",
            }
        )
    for i in linked_invs:
        evidence.append(
            {
                "id": i.id,
                "kind": "invoice",
                "label": f"Invoice · {i.part} x {i.quantity}",
                "detail": "Covers delivery note(s) " + ", ".join(i.delivery_notes) + ".",
                "source": "source/initial.json",
            }
        )
    for o in ctx.observations:
        if o.source_record:
            continue
        evidence.append(
            {
                "id": o.id,
                "kind": o.kind,
                "label": o.label or o.id,
                "detail": "Simulated interaction event — not a supplied record.",
                "source": "SIMULATED (not in source/initial.json)",
            }
        )

    return {
        "engine_version": ENGINE_VERSION,
        "quantities": {
            "received": received,
            "damaged": damaged,
            "accepted": accepted,
            "invoiced": invoiced,
            "listed": listed,
            "possible_shortage": shortage,
            "overage": overage,
            "unlisted_arrivals": unlisted_arrivals,
            "unidentified_scans": len(unidentified),
        },
        "conclusions": [c.__dict__ for c in conclusions],
        "evidence": evidence,
        "rules": list(records.rules),
        "record_fingerprint": records.sha256,
        "record_source": "source/initial.json",
    }


def diagnose(computed: dict[str, Any], ctx: EvidenceContext, records: Records) -> dict[str, Any]:
    """Deterministic rule table. First matching rule wins — order matters."""
    q = computed["quantities"]
    part = (
        ctx.facts.part_number
        if ctx.facts is not None and ctx.facts.part_number
        else (records.orders[0].part if records.orders else "part")
    )
    unidentified = [o for o in ctx.observations if o.kind == "repeated_scan" and not o.package_identity]

    if unidentified:
        return {
            "status": "insufficient_evidence",
            "code": "REPEATED_SCAN_UNIDENTIFIED",
            "headline": "Repeated scan without unique package identity — quantity not changed",
            "explanation": (
                "A further scan was recorded at the bay with no unique package identity. The supplied "
                'rule "one scan is not necessarily one new delivery" applies, so the received quantity '
                f"stays at {q['received']} and no automatic change is made."
            ),
            "evidence_insufficient": True,
            "requires_reviewer_confirmation": True,
            "evidence": [o.id for o in unidentified],
            "confidence": "unknown",
        }

    if q["invoiced"] is None:
        return {
            "status": "insufficient_evidence",
            "code": "AWAITING_EVIDENCE",
            "headline": "No invoice linked — shortage cannot be calculated",
            "explanation": "Link the invoice before any comparison between arrival and billing is drawn.",
            "evidence_insufficient": True,
            "requires_reviewer_confirmation": True,
            "evidence": [],
            "confidence": "unknown",
        }

    if q["possible_shortage"]:
        return {
            "status": "open",
            "code": "POSSIBLE_SHORTAGE",
            "headline": f"Possible shortage of {q['possible_shortage']} x {part}",
            "explanation": (
                f"The invoice bills {q['invoiced']} unit(s) while {q['received']} unit(s) were confirmed "
                f"received across the linked receipt observations. The difference of {q['possible_shortage']} "
                "unit(s) is a possible shortage — or a consignment that has not arrived yet. With the linked "
                "evidence the two are indistinguishable."
            ),
            "evidence_insufficient": False,
            "requires_reviewer_confirmation": False,
            "evidence": [i for i in (records.invoices[0].id if records.invoices else "") if i]
            + [o.source_record for o in ctx.observations if o.source_record],
            "confidence": "low",
        }

    if q["overage"]:
        return {
            "status": "open",
            "code": "ARRIVAL_NOT_COVERED",
            "headline": f"Received {q['overage']} unit(s) more than the invoice bills",
            "explanation": (
                f"{q['received']} unit(s) were received against {q['invoiced']} invoiced. An arrival without "
                "a matching invoice line needs a second delivery note or a credit."
            ),
            "evidence_insufficient": False,
            "requires_reviewer_confirmation": True,
            "evidence": [i.id for i in (records.invoice(x) for x in ctx.invoice_ids) if i is not None],
            "confidence": "low",
        }

    if q["damaged"]:
        return {
            "status": "open",
            "code": "DAMAGE_ONLY",
            "headline": f"Quantities match the invoice; {q['damaged']} damaged unit(s) not accepted",
            "explanation": (
                f"Received {q['received']} unit(s) match the {q['invoiced']} invoiced. {q['damaged']} unit(s) "
                f"were recorded as damaged, so the accepted quantity is {q['accepted']}. The earlier shortage "
                "signal was a staged delivery, not a missing consignment."
            ),
            "evidence_insufficient": False,
            "requires_reviewer_confirmation": False,
            "evidence": [o.source_record for o in ctx.observations if o.source_record],
            "confidence": "high",
        }

    return {
        "status": "resolved",
        "code": "MATCHED",
        "headline": f"Received, invoiced and accepted quantities agree on {part}",
        "explanation": (
            f"{q['received']} unit(s) received, {q['accepted']} accepted, {q['invoiced']} invoiced. "
            "No discrepancy to review."
        ),
        "evidence_insufficient": False,
        "requires_reviewer_confirmation": False,
        "evidence": [o.source_record for o in ctx.observations if o.source_record],
        "confidence": "high",
    }


NEXT_ACTIONS: dict[str, str] = {
    "POSSIBLE_SHORTAGE": (
        "Ask the supplier to confirm whether the remaining {n} unit(s) are covered by a second delivery "
        "note, or confirm that the first note was a partial shipment. Hold any shortage claim until that "
        "evidence arrives."
    ),
    "DAMAGE_ONLY": (
        "Record the {n} damaged unit(s) for supplier review (replacement or credit). The accepted quantity "
        "stays at {accepted}."
    ),
    "MATCHED": "Close the receipt observation and file the linked evidence for the next consignment.",
    "REPEATED_SCAN_UNIDENTIFIED": (
        "Reviewer must confirm whether the repeated scan is the same physical package. Until then the "
        "received quantity stays at {received}; no automatic increase is applied."
    ),
    "ARRIVAL_NOT_COVERED": (
        "Request the delivery note covering the extra {n} unit(s), or route them to a separate receipt "
        "observation. No automatic correction."
    ),
    "AWAITING_EVIDENCE": "Link the invoice (and the delivery note it covers) before reviewing a discrepancy.",
}


def next_action(diagnosis: dict[str, Any], computed: dict[str, Any]) -> dict[str, str]:
    q = computed["quantities"]
    n = q["possible_shortage"] if diagnosis["code"] == "POSSIBLE_SHORTAGE" else q["damaged"]
    text = NEXT_ACTIONS[diagnosis["code"]].format(n=n, accepted=q["accepted"], received=q["received"])
    return {
        "text": text,
        "owner": "Receiving lead (reviewer)",
        "executed_by_prototype": "no",
        "note": "No inventory, accounting or supplier action is executed.",
    }
